"""Example flowcharts served as resources and used by the tests."""

from __future__ import annotations

from typing import Any, Dict

ORDER_PROCESSING: Dict[str, Any] = {
    "title": "Process customer order",
    "chart_type": "program",
    "direction": "TB",
    "nodes": [
        {"id": "start", "type": "terminator", "text": "Start"},
        {"id": "read_order", "type": "data", "text": "Read order"},
        {"id": "order_valid", "type": "decision", "text": "Order data valid?"},
        {"id": "write_rejection", "type": "data", "text": "Write rejection notice"},
        {"id": "in_stock", "type": "decision", "text": "All items in stock?"},
        {"id": "backorder", "type": "predefined_process", "text": "Create backorder"},
        {"id": "charge", "type": "predefined_process", "text": "Charge payment"},
        {"id": "approved", "type": "decision", "text": "Payment approved?"},
        {"id": "write_decline", "type": "data", "text": "Write payment-declined notice"},
        {"id": "schedule", "type": "process", "text": "Schedule shipment"},
        {"id": "confirm", "type": "data", "text": "Write order confirmation"},
        {"id": "end", "type": "terminator", "text": "End"},
        {"id": "note_charge", "type": "annotation",
         "text": "Gateway retries (max 3) happen inside Charge payment",
         "annotates": ["charge"]},
    ],
    "edges": [
        {"from": "start", "to": "read_order"},
        {"from": "read_order", "to": "order_valid"},
        {"from": "order_valid", "to": "in_stock", "label": "Yes"},
        {"from": "order_valid", "to": "write_rejection", "label": "No"},
        {"from": "write_rejection", "to": "end"},
        {"from": "in_stock", "to": "charge", "label": "Yes"},
        {"from": "in_stock", "to": "backorder", "label": "No"},
        {"from": "backorder", "to": "end"},
        {"from": "charge", "to": "approved"},
        {"from": "approved", "to": "schedule", "label": "Yes"},
        {"from": "approved", "to": "write_decline", "label": "No"},
        {"from": "write_decline", "to": "end"},
        {"from": "schedule", "to": "confirm"},
        {"from": "confirm", "to": "end"},
    ],
}

MONTHLY_BILLING: Dict[str, Any] = {
    "title": "Generate monthly invoices",
    "chart_type": "program",
    "direction": "TB",
    "nodes": [
        {"id": "start", "type": "terminator", "text": "Start"},
        {"id": "init", "type": "preparation", "text": "Set invoice count = 0"},
        {"id": "loop_begin", "type": "loop_limit", "role": "begin", "loop_id": "L1",
         "text": "For each active customer"},
        {"id": "read_usage", "type": "data", "text": "Read customer usage"},
        {"id": "usage_found", "type": "decision", "text": "Usage record found?"},
        {"id": "calculate", "type": "predefined_process", "text": "Calculate invoice"},
        {"id": "write_invoice", "type": "data", "text": "Write invoice"},
        {"id": "count", "type": "process", "text": "Add 1 to invoice count"},
        {"id": "write_exception", "type": "data", "text": "Write missing-usage exception"},
        {"id": "loop_end", "type": "loop_limit", "role": "end", "loop_id": "L1",
         "text": "Until no customer left"},
        {"id": "to_summary", "type": "connector", "text": "A"},
        {"id": "from_summary", "type": "connector", "text": "A"},
        {"id": "summary", "type": "data", "text": "Write billing summary"},
        {"id": "end", "type": "terminator", "text": "End"},
    ],
    "edges": [
        {"from": "start", "to": "init"},
        {"from": "init", "to": "loop_begin"},
        {"from": "loop_begin", "to": "read_usage"},
        {"from": "read_usage", "to": "usage_found"},
        {"from": "usage_found", "to": "calculate", "label": "Yes"},
        {"from": "usage_found", "to": "write_exception", "label": "No"},
        {"from": "calculate", "to": "write_invoice"},
        {"from": "write_invoice", "to": "count"},
        {"from": "count", "to": "loop_end"},
        {"from": "write_exception", "to": "loop_end"},
        {"from": "loop_end", "to": "to_summary"},
        {"from": "from_summary", "to": "summary"},
        {"from": "summary", "to": "end"},
    ],
}

REFUND_REQUEST: Dict[str, Any] = {
    "title": "Handle refund request",
    "chart_type": "system",
    "direction": "TB",
    "nodes": [
        {"id": "start", "type": "terminator", "text": "Refund request received"},
        {"id": "read_request", "type": "data", "text": "Read refund request"},
        {"id": "find_order", "type": "process", "text": "Look up order"},
        {"id": "order_found", "type": "decision", "text": "Order found?"},
        {"id": "in_policy", "type": "decision", "text": "Within refund policy?"},
        {"id": "policy_note", "type": "annotation",
         "text": "Policy P-12: bought <= 30 days ago and not refunded before",
         "annotates": ["in_policy"]},
        {"id": "large", "type": "decision", "text": "Amount > 500 EUR?"},
        {"id": "review", "type": "manual_operation", "text": "Manager reviews refund"},
        {"id": "approved", "type": "decision", "text": "Approved within 48 h?"},
        {"id": "refund", "type": "predefined_process", "text": "Issue refund"},
        {"id": "refund_ok", "type": "decision", "text": "Refund succeeded?"},
        {"id": "escalate", "type": "process", "text": "Escalate to finance team"},
        {"id": "write_confirmation", "type": "data", "text": "Write refund confirmation"},
        {"id": "write_rejection", "type": "data", "text": "Write rejection with reason"},
        {"id": "end_refunded", "type": "terminator", "text": "End: refunded"},
        {"id": "end_rejected", "type": "terminator", "text": "End: rejected"},
        {"id": "end_escalated", "type": "terminator", "text": "End: escalated"},
    ],
    "edges": [
        {"from": "start", "to": "read_request"},
        {"from": "read_request", "to": "find_order"},
        {"from": "find_order", "to": "order_found"},
        {"from": "order_found", "to": "in_policy", "label": "Yes"},
        {"from": "order_found", "to": "write_rejection", "label": "No"},
        {"from": "in_policy", "to": "large", "label": "Yes"},
        {"from": "in_policy", "to": "write_rejection", "label": "No"},
        {"from": "large", "to": "review", "label": "Yes"},
        {"from": "large", "to": "refund", "label": "No"},
        {"from": "review", "to": "approved"},
        {"from": "approved", "to": "refund", "label": "Yes"},
        {"from": "approved", "to": "write_rejection", "label": "No"},
        {"from": "refund", "to": "refund_ok"},
        {"from": "refund_ok", "to": "write_confirmation", "label": "Yes"},
        {"from": "refund_ok", "to": "escalate", "label": "No"},
        {"from": "escalate", "to": "end_escalated"},
        {"from": "write_confirmation", "to": "end_refunded"},
        {"from": "write_rejection", "to": "end_rejected"},
    ],
}

FLAWED_LOGIN: Dict[str, Any] = {
    "title": "User login (flawed on purpose)",
    "chart_type": "program",
    "nodes": [
        {"id": "s", "type": "start", "text": "Begin"},
        {"id": "input", "type": "process", "text": "Get user name and password"},
        {"id": "audit", "type": "process", "text": "Log attempt"},
        {"id": "check", "type": "diamond", "text": "credentials"},
        {"id": "save", "type": "process", "text": "Save session?"},
        {"id": "show_error", "type": "document", "text": "Show error"},
        {"id": "jump", "type": "connector", "text": "A"},
        {"id": "note", "type": "annotation", "text": "Passwords are hashed"},
    ],
    "edges": [
        {"from": "s", "to": "input"},
        {"from": "input", "to": "check"},
        {"from": "input", "to": "audit"},
        {"from": "check", "to": "save", "label": "yes"},
        {"from": "check", "to": "show_error"},
        {"from": "show_error", "to": "input"},
        {"from": "save", "to": "jump"},
        {"from": "note", "to": "check"},
    ],
}

EXAMPLES = {
    "order-processing": ORDER_PROCESSING,
    "monthly-billing": MONTHLY_BILLING,
    "refund-request": REFUND_REQUEST,
    "flawed-login": FLAWED_LOGIN,
}
